global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['collector:8888']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(cl_dropped_samples_total|cl_keys_used|apq_fill_ratio|apq_class_size|apq_spill_total|dlq_utilization_ratio|dlq_oldest_age_seconds|dlq_corrupted_total|go_gc_duration_seconds)'
        action: keep

  - job_name: 'mock-upstream'
    static_configs:
      - targets: ['mock-upstream:8889']

  - job_name: 'workload-generator'
    static_configs:
      - targets: ['workload:9464']
